# Vagrantfile
# - 1 master + 2 worker node tanımı
# - Her VM için: box (ubuntu/jammy64), CPU, RAM ayarları
# - Private network IP atamaları (örn. 192.168.56.10/11/12)
# - Shared provisioning: scripts/common.sh tüm node'larda çalışır
# - Master için scripts/master.sh provision
# - Worker'lar için scripts/worker.sh provision

IMAGE_NAME = "ubuntu/jammy64"
N_WORKERS = 2

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  
  # --- MASTER NODE ---
  config.vm.define "k8s-master" do |master|
    master.vm.box = IMAGE_NAME
    master.vm.network "private_network", ip: "192.168.56.10"
    master.vm.hostname = "k8s-master"
    
    # Virtualbox sağlayıcı bloğu
    master.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end # <-- Provider bloğunu kapatır
    
    master.vm.provision "shell", path: "scripts/common.sh"
    master.vm.provision "shell", path: "scripts/master.sh"
  end # <-- Master node tanım bloğunu kapatır

  # --- WORKER NODES ---
  # Döngü bloğu başlangıcı
  (1..N_WORKERS).each do |i|
    
    config.vm.define "k8s-worker-#{i}" do |worker|
      worker.vm.box = IMAGE_NAME
      worker.vm.network "private_network", ip: "192.168.56.1#{i}"
      worker.vm.hostname = "k8s-worker-#{i}"
      
      # Virtualbox sağlayıcı bloğu
      worker.vm.provider "virtualbox" do |v|
        v.memory = 1536
        v.cpus = 2
      end # <-- Provider bloğunu kapatır
      
      worker.vm.provision "shell", path: "scripts/common.sh"
      worker.vm.provision "shell", path: "scripts/worker.sh"
    end # <-- Worker node tanım bloğunu kapatır
    
  end # <-- Döngü (each) bloğunu kapatır

end # <-- En dıştaki Vagrant.configure bloğunu kapatır